server.port=${PORT:8080}
logging.level.org.atmosphere = warn
spring.mustache.check-template-location = false

vaadin.launch-browser=true
vaadin.allowed-packages = com.vaadin,org.vaadin,com.flowingcode,dev.app.rentingCar_boot

spring.jpa.defer-datasource-initialization = true


spring.datasource.url=jdbc:h2:file:/home/mateo/Descargas/MF04-05-Mateo/dataBase/rentingcar
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=   # ? VACÍO (sin nada)

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true