server.port=${PORT:8081}
logging.level.org.atmosphere=warn
spring.mustache.check-template-location=false

vaadin.launch-browser=true
vaadin.allowed-packages=com.vaadin,org.vaadin,com.flowingcode,dev.app.rentingcarvaadin

spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# ESTO ES LO QUE FUNCIONA EN rentingCar-vaadin
spring.datasource.url=jdbc:h2:mem:rentingdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console