server.port=${PORT:8080}
logging.level.org.atmosphere=warn
spring.mustache.check-template-location=false

vaadin.launch-browser=true
vaadin.allowed-packages = com.vaadin,org.vaadin,com.flowingcode,dev.app.rentingcarvaadin
spring.jpa.defer-datasource-initialization=true

spring.datasource.url=jdbc:h2:mem:rentingdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=mateo
spring.datasource.password=1234

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update